### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by ancestor-mithril** [hhaentze/MRSegmentator#9]
Firstly, thank you for releasing the weights for the model, it is an excellent work!

May I ask if you plan to release the training data? I noticed the arxiv paper talks about this.

**Comment by hhaentze** [comment]
Unfortunately we cannot release the training data. The NAKO and UKBB datasets are already publicly available but you need a license to access them. Concerning our in-house dataset, our hospital's data protection laws make it very challenging to share it.

The specific sentence in our arxiv paper that sais otherwise is regrettably incorrect. We need to update this, thanks for pointing it out!
